apiVersion: apps/v1
kind: Deployment
metadata:
  name: cursos-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cursos-app
  template:
    metadata:
      labels:
        app: cursos-app
    spec:
      containers:
        - name: cursos-app
          image: coelhosgabi/cursos-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/mysql"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "0.5"