apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER: Z2FicmllbGE=
  MYSQL_PASSWORD: c2VuaGEyMzM=
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
